title: Leo Wang
logo: /assets/img/profile-pic.jpg
description: 
# Hey, I'm Leo. Welcome to my site! ✌️   
# I just finished my first year studying CS and Physics at the University of Toronto. I play the guitar, piano and basketball in my free time.
# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
